
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int opAsignacion = 12;
  public static final int realExponencial = 59;
  public static final int opIgual = 33;
  public static final int opMultiplicacion = 15;
  public static final int estElse = 24;
  public static final int devolver = 42;
  public static final int programa = 46;
  public static final int opNot = 32;
  public static final int opAnd = 31;
  public static final int dosPuntos = 48;
  public static final int estUntil = 28;
  public static final int opDivision = 16;
  public static final int estThen = 23;
  public static final int coma = 7;
  public static final int doPR = 55;
  public static final int identificador = 2;
  public static final int estIf = 22;
  public static final int procedimiento = 53;
  public static final int begin = 51;
  public static final int estRepetir = 29;
  public static final int opMenos = 14;
  public static final int cerrarLl = 6;
  public static final int real = 10;
  public static final int opMenor = 34;
  public static final int downto = 56;
  public static final int variables = 47;
  public static final int end = 52;
  public static final int escribir = 62;
  public static final int opMayor = 35;
  public static final int realDecimal = 60;
  public static final int opMenorIgual = 36;
  public static final int opModulo = 17;
  public static final int estWhile = 26;
  public static final int EOF = 0;
  public static final int constRealMixto = 44;
  public static final int constRealExp = 43;
  public static final int error = 1;
  public static final int realMixto = 58;
  public static final int opMayorIgual = 37;
  public static final int entero = 9;
  public static final int cero = 19;
  public static final int abrirLl = 5;
  public static final int punto = 38;
  public static final int opOr = 30;
  public static final int funcion = 54;
  public static final int vacio = 8;
  public static final int constEntera = 18;
  public static final int constLit = 21;
  public static final int puntoComa = 11;
  public static final int cerrarP = 4;
  public static final int define = 41;
  public static final int estFor = 25;
  public static final int estDo = 27;
  public static final int unit = 50;
  public static final int opMas = 13;
  public static final int cerrarC = 39;
  public static final int abrirP = 3;
  public static final int enteroDecimal = 57;
  public static final int constante = 49;
  public static final int constReal = 20;
  public static final int to = 45;
  public static final int abrirC = 40;
  public static final int constanteLiteral = 61;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identificador",
  "abrirP",
  "cerrarP",
  "abrirLl",
  "cerrarLl",
  "coma",
  "vacio",
  "entero",
  "real",
  "puntoComa",
  "opAsignacion",
  "opMas",
  "opMenos",
  "opMultiplicacion",
  "opDivision",
  "opModulo",
  "constEntera",
  "cero",
  "constReal",
  "constLit",
  "estIf",
  "estThen",
  "estElse",
  "estFor",
  "estWhile",
  "estDo",
  "estUntil",
  "estRepetir",
  "opOr",
  "opAnd",
  "opNot",
  "opIgual",
  "opMenor",
  "opMayor",
  "opMenorIgual",
  "opMayorIgual",
  "punto",
  "cerrarC",
  "abrirC",
  "define",
  "devolver",
  "constRealExp",
  "constRealMixto",
  "to",
  "programa",
  "variables",
  "dosPuntos",
  "constante",
  "unit",
  "begin",
  "end",
  "procedimiento",
  "funcion",
  "doPR",
  "downto",
  "enteroDecimal",
  "realMixto",
  "realExponencial",
  "realDecimal",
  "constanteLiteral",
  "escribir"
  };
}

